import React from 'react'
import { PiArrowUpRight } from 'react-icons/pi'

import SaunaLogo from '@/components/logo'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { cn } from '@/lib/utils'

export const SaunaCard: React.FC = () => {
  return (
    <Card className={cn(`relative w-full overflow-hidden rounded-2xl border bg-opacity-5 px-4 pb-4`)}>
      <CardHeader className="flex w-full flex-col items-start">
        <CardTitle className="flex w-full items-center justify-between py-2 pb-4 text-2xl">
          <div className="flex items-center gap-3">
            <SaunaLogo
              emblemOnly
              color={'black'}
              width={26}
            />
            <span className={`text-xl font-light text-gray-900`}>Drowning in busywork?</span>
          </div>
        </CardTitle>
        <div className="w-full border-b border-gray-300" />
      </CardHeader>
      <CardContent className="flex flex-col space-y-2 text-gray-700">
        This analysis was generated by an AI agent — Sauna gives you one as a full-time coworker.
        <br />
        <p>It learns how you work, remembers what matters, and acts on it: drafting messages in your voice, tracking priorities, and delivering briefings across the tools you already use.</p>
        <br />
        <p>The first multiplayer AI, built for your whole team.</p>
        <div className="mt-8 py-4">
          <Button
            size={'sm'}
            variant={'default'}
            asChild>
            <a
              href="https://sauna.ai"
              target="_blank"
              className="flex-center gap-2">
              <SaunaLogo
                emblemOnly
                color={'white'}
                width={12}
              />
              <p>Meet Sauna</p>
              <PiArrowUpRight />
            </a>
          </Button>
        </div>
      </CardContent>
    </Card>
  )
}
