import {
  PiBarbell,
  PiBuildings,
  PiChatCircle,
  PiChatTeardrop,
  PiChecks,
  PiClock,
  PiCurrencyDollar,
  PiFire,
  PiFlame,
  PiHandHeart,
  PiHandsPraying,
  PiHeart,
  PiHeartBreak,
  PiLightbulb,
  PiLightning,
  PiMoney,
  PiMoon,
  PiPawPrint,
  PiPercent,
  PiPlant,
  PiRocket,
  PiScissors,
  PiSmileyXEyes,
  PiStar,
  PiSword,
  PiTarget,
  PiUsers,
  PiWallet,
  PiWarning,
} from 'react-icons/pi'

/**
 * Configuration for card data used in the application.
 * Each object in the array represents a card with specific properties.
 *
 * @typedef {Object} CardConfig
 * @property {string} title - The title of the card.
 * @property {IconType} icon - The icon component from react-icons/pi.
 * @property {string} contentKey - The key used to fetch content for this card.
 * @property {string} colorClass - The Tailwind CSS class for text color.
 * @property {string} color - The color name used for styling.
 * @property {string} bg - The Tailwind CSS class for background color.
 * @property {boolean} [wide] - Optional. If true, the card will be wider.
 */

/**
 * Array of card configurations.
 * @type {CardConfig[]}
 */
export const cardData = [
  {
    title: 'Roast',
    icon: PiFire,
    contentKey: 'roast',
    colorClass: 'text-red-500',
    color: 'red',
    bg: 'bg-red-500',
    wide: true, // This card will be displayed wider than others
  },
  {
    title: 'Strengths',
    icon: PiFlame,
    contentKey: 'strengths',
    colorClass: 'text-orange-500',
    color: 'orange',
    bg: 'bg-orange-500',
  },
  {
    title: 'Weaknesses',
    icon: PiMoon,
    contentKey: 'weaknesses',
    colorClass: 'text-blue-500',
    color: 'blue',
    bg: 'bg-blue-500',
  },
  {
    title: 'Love Life',
    icon: PiHeart,
    contentKey: 'loveLife',
    colorClass: 'text-red-500',
    color: 'red',
    bg: 'bg-red-500',
  },
  {
    title: 'Money',
    icon: PiMoney,
    contentKey: 'money',
    colorClass: 'text-green-500',
    color: 'green',
    bg: 'bg-green-500',
  },
  {
    title: 'Health',
    icon: PiBarbell,
    contentKey: 'health',
    colorClass: 'text-indigo-500',
    color: 'indigo',
    bg: 'bg-indigo-500',
  },
  {
    title: "Other's Perspective",
    icon: PiUsers,
    contentKey: 'colleaguePerspective',
    colorClass: 'text-yellow-500',
    color: 'yellow',
    bg: 'bg-yellow-500',
  },
  {
    title: 'Biggest Goal',
    icon: PiRocket,
    contentKey: 'biggestGoal',
    colorClass: 'text-purple-500',
    color: 'purple',
    bg: 'bg-purple-500',
  },
  {
    title: 'Famous Person like You',
    icon: PiStar,
    contentKey: 'famousPersonComparison',
    colorClass: 'text-emerald-500',
    color: 'emerald',
    bg: 'bg-emerald-500',
  },
  {
    title: 'Pickup Lines',
    icon: PiChatTeardrop,
    contentKey: 'pickupLines',
    colorClass: 'text-pink-500',
    color: 'pink',
    bg: 'bg-pink-500',
  },
  {
    title: 'Previous Life',
    icon: PiHandsPraying,
    contentKey: 'previousLife',
    colorClass: 'text-gray-500',
    color: 'gray',
    bg: 'bg-gray-500',
  },
  {
    title: 'Animal',
    icon: PiPawPrint,
    contentKey: 'animal',
    colorClass: 'text-sky-500',
    color: 'sky',
    bg: 'bg-sky-500',
  },
  {
    title: 'Thing to Buy',
    icon: PiWallet,
    contentKey: 'fiftyDollarThing',
    colorClass: 'text-fuchsia-500',
    color: 'fuchsia',
    bg: 'bg-fuchsia-500',
  },
  {
    title: 'Career',
    icon: PiLightbulb,
    contentKey: 'career',
    colorClass: 'text-amber-500',
    color: 'amber',
    bg: 'bg-amber-500',
  },
  {
    title: 'Life Suggestion',
    icon: PiPlant,
    contentKey: 'lifeSuggestion',
    colorClass: 'text-teal-500',
    color: 'teal',
    bg: 'bg-teal-500',
  },
]

// Note: This configuration is used to generate cards in the UI.
// Each card represents a different aspect or category of information.
// The 'icon', 'colorClass', and 'bg' properties are used for styling.
// The 'contentKey' is used to fetch the appropriate content for each card.

export const compatibilityCardData = [
  {
    title: 'Person One Personality',
    icon: PiUsers,
    contentKey: 'personOnePersonality',
    colorClass: 'text-blue-500',
    color: 'blue',
    bg: 'bg-blue-500',
  },
  {
    title: 'Person Two Personality',
    icon: PiUsers,
    contentKey: 'personTwoPersonality',
    colorClass: 'text-green-500',
    color: 'green',
    bg: 'bg-green-500',
  },
  {
    title: 'Personality Type Match',
    icon: PiHeart,
    contentKey: 'personalityTypeMatch',
    colorClass: 'text-purple-500',
    color: 'purple',
    bg: 'bg-purple-500',
  },
  {
    title: 'Characteristics',
    icon: PiChecks,
    contentKey: 'characteristics',
    colorClass: 'text-yellow-500',
    color: 'yellow',
    bg: 'bg-yellow-500',
  },
  {
    title: 'Threat',
    icon: PiWarning,
    contentKey: 'threat',
    colorClass: 'text-red-500',
    color: 'red',
    bg: 'bg-red-500',
  },
  {
    title: 'Crazy',
    icon: PiSmileyXEyes,
    contentKey: 'crazy',
    colorClass: 'text-pink-500',
    color: 'pink',
    bg: 'bg-pink-500',
  },
  {
    title: 'Dynamic',
    icon: PiLightning,
    contentKey: 'dynamic',
    colorClass: 'text-orange-500',
    color: 'orange',
    bg: 'bg-orange-500',
  },
  {
    title: 'Financial Compatibility',
    icon: PiCurrencyDollar,
    contentKey: 'financialCompatibility',
    colorClass: 'text-green-500',
    color: 'green',
    bg: 'bg-green-500',
  },
  {
    title: 'Emotional Compatibility',
    icon: PiHeart,
    contentKey: 'emotionalCompatibility',
    colorClass: 'text-red-500',
    color: 'red',
    bg: 'bg-red-500',
  },
  {
    title: 'Communication Style Compatibility',
    icon: PiChatCircle,
    contentKey: 'communicationstyleCompatibility',
    colorClass: 'text-blue-500',
    color: 'blue',
    bg: 'bg-blue-500',
  },
  {
    title: 'Disagreements',
    icon: PiSword,
    contentKey: 'disagreements',
    colorClass: 'text-gray-500',
    color: 'gray',
    bg: 'bg-gray-500',
  },
  {
    title: 'Goals Alignment',
    icon: PiTarget,
    contentKey: 'goalsAligment',
    colorClass: 'text-indigo-500',
    color: 'indigo',
    bg: 'bg-indigo-500',
  },
  {
    title: 'Free Time',
    icon: PiClock,
    contentKey: 'freeTime',
    colorClass: 'text-teal-500',
    color: 'teal',
    bg: 'bg-teal-500',
  },
  {
    title: 'Breakup Percentage',
    icon: PiHeartBreak,
    contentKey: 'breakupPercentage',
    colorClass: 'text-red-500',
    color: 'red',
    bg: 'bg-red-500',
  },
  {
    title: 'Making Millions With Idea',
    icon: PiLightbulb,
    contentKey: 'makingMillionsWithIdea',
    colorClass: 'text-yellow-500',
    color: 'yellow',
    bg: 'bg-yellow-500',
  },
  {
    title: 'Best Idea To Work On',
    icon: PiRocket,
    contentKey: 'bestIdeaToWork',
    colorClass: 'text-purple-500',
    color: 'purple',
    bg: 'bg-purple-500',
  },
  {
    title: 'YC',
    icon: PiBuildings,
    contentKey: 'yc',
    colorClass: 'text-orange-500',
    color: 'orange',
    bg: 'bg-orange-500',
  },
  {
    title: 'Marriage',
    icon: PiHandHeart,
    contentKey: 'marriage',
    colorClass: 'text-pink-500',
    color: 'pink',
    bg: 'bg-pink-500',
  },
  {
    title: 'Divorce',
    icon: PiScissors,
    contentKey: 'divorce',
    colorClass: 'text-gray-500',
    color: 'gray',
    bg: 'bg-gray-500',
  },
  {
    title: 'Overall Compatibility',
    icon: PiPercent,
    contentKey: 'overallCompability',
    colorClass: 'text-green-500',
    color: 'green',
    bg: 'bg-green-500',
  },
]
